apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "diffusion"
  namespace: saiyam
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    containers:
      - image: saiyam911/navigateaustin:v5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "12"
            memory: "18Gi"
          requests:
            cpu: "12"
            memory: "18Gi"
